# Generated by Django 2.2.2 on 2019-07-08 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0003_auto_20190708_1150"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="creator",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
