# Generated by Django 2.2.2 on 2019-09-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0005_auto_20190813_1237"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="admin_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
