# Generated by Django 2.2.2 on 2019-09-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_admin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
