# Generated by Django 2.2.5 on 2019-09-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_auto_20190916_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='admin_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link a administración del campus'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_finish',
            field=models.DateTimeField(verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_start',
            field=models.DateTimeField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=20000, verbose_name='Descripción de la actividad'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='in_charge',
            field=models.CharField(max_length=200, verbose_name='Correo de encargado'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la actividad'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='state',
            field=models.CharField(choices=[('A', 'Aprobada'), ('R', 'Rechazada'), ('P', 'Pendiente'), ('C', 'Cancelada'), ('PA', 'En revisión por Decanato'), ('PC', 'En revisión por CAi')], default='PC', max_length=2, verbose_name='Estado de la solicitud'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de equipamiento'),
        ),
        migrations.AlterField(
            model_name='space',
            name='admin_required',
            field=models.BooleanField(verbose_name='¿Requiere de link de administración?'),
        ),
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Descripción de espacio'),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de espacio'),
        ),
    ]
