# Generated by Django 2.2.5 on 2019-09-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0016_auto_20190924_2242"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="color",
            field=models.CharField(default="rgb(0,0,0)", max_length=20),
        ),
    ]
