# Generated by Django 2.2.5 on 2019-09-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0018_auto_20190925_2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="in_charge",
            field=models.EmailField(max_length=200, verbose_name="Correo de encargado"),
        ),
    ]
