# Generated by Django 4.2.3 on 2023-11-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0020_coordinator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coordinator",
            options={"verbose_name": "Coordinador CAi", "verbose_name_plural": "Coordinador CAi (solo tener 1)"},
        ),
        migrations.AlterField(
            model_name="activity",
            name="admin_link",
            field=models.URLField(blank=True, default="", verbose_name="Link a administración del campus"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(blank=True, max_length=20000, verbose_name="Descripción de la actividad"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="coordinator",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="space",
            name="description",
            field=models.CharField(blank=True, default="", max_length=2000, verbose_name="Descripción de espacio"),
        ),
        migrations.AlterField(
            model_name="space",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
