# Generated by Django 2.2.2 on 2019-09-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_auto_20190813_1237"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="administrative",
            field=models.BooleanField(default=False),
        ),
    ]
